### ISSUE TITLE
Cannot launch app through steam on windows -- Fossilize Failed to parse ApplicationInfo

### ISSUE THREAD

**Issue by Braymatter** [Noxime/steamworks-rs#116]
I've got a weird problem. When I launch my app through steam on OSX it works totally fine as expected.

When I launch it through steam on windows I get some Fossilize Error about failing to parse Application Info I'm guessing I'm missing some manifest file?

Launching the game through the executable directly works fine.

Anyone have any ideas on what could be causing this?

Actual Error:
Error: Failed to parse ApplicationInfoFilter, letting recording go through
INFO: Overriding serialization path : "E:/SteamLibray/steamapps/shadercache/2248000/fozpipelinesv6/steamapprun_pipeline_cache".

I'm unable to find any resources on the web for this except for the ErrorMessage in the Fossilize Repository, and no one seems to know what the cause is

I'm running on an NVIDIA 3070 with a Vulkan backend

**Comment by Noxime** [comment]
I am not familiar with Fossilize, but from a quick look around it seems to be a caching system for Vulkan objects. I assume on macOS this is not an issue, as Metal is used instead of Vulkan. 

This caching system is not part of steamworks-rs, so we cannot do much here and the problem is more to do with the graphics API you use. My gut recommendation would be to just clear your shader cache and try again.
